updated buildtx api
renproject/multichain pull request #128
Opened 2021-10-12 03:29 UTC by gdsoumya

This PR updates the BuildTx api to receive a pubkey of the sender instead of a string address.

2021-10-12 03:45 UTC, jazg requested changes
Nice stuff! Just left some minor comments.

2021-10-12 03:45 UTC, jazg commented on chain/filecoin/account.go
> +	eth_crypto "github.com/ethereum/go-ethereum/crypto"
```suggestion
	ethcrypto "github.com/ethereum/go-ethereum/crypto"
```

Renaming this for consistency with other imports.

2021-10-12 03:45 UTC, jazg commented on chain/filecoin/account.go
> +	pubKeyUncompressed := eth_crypto.FromECDSAPub((*ecdsa.PublicKey)(fromPubKey))
```suggestion
	pubKeyUncompressed := ethcrypto.FromECDSAPub((*ecdsa.PublicKey)(fromPubKey))
```

2021-10-12 03:45 UTC, jazg commented on chain/filecoin/account.go
> +		return nil, fmt.Errorf("bad from pubkey address '%v': %v", fromPubKey, err)
```suggestion
		return nil, fmt.Errorf("bad from pubkey: %v", err)
```

Can remove this since it's no longer a readable address.

2021-10-13 09:28 UTC, roynalnaruto approved these changes
Looks good!

2021-10-13 09:28 UTC, merged