feat: client to expose latest block api
renproject/multichain pull request #66
Opened 2020-12-01 11:47 UTC by roynalnaruto

Adds the method:
```go
func (client *Client) LatestBlock(ctx context.Context) (pack.U64, error) 
```

to both the `utxo.Client` as well as `account.Client`. Tested for:
- [x] Bitcoin
- [x] Bitcoin Cash
- [x] Dogecoin
- [x] Zcash
- [x] Filecoin
- [x] Terra

2020-12-01 11:53 UTC, loongy approved these changes
LGTM, thanks @roynalnaruto!

2020-12-01 22:24 UTC, jazg commented
@roynalnaruto Any idea what's causing the tests to fail?

2020-12-01 22:26 UTC, jazg approved these changes

2020-12-02 07:29 UTC, roynalnaruto commented
> @roynalnaruto Any idea what's causing the tests to fail?

I'll go through it. It's the Bitcoin Cash tests that are failing.

2020-12-02 12:40 UTC, loongy requested changes

2020-12-02 12:40 UTC, loongy commented on chain/bitcoin/bitcoin.go
> +
Need to bounds check the int64 to make sure that it is not negative before casting it to a U64. If it is negative, return an error.

2020-12-02 12:40 UTC, loongy commented on chain/filecoin/client.go
> +
Same as previous comment, make sure to check negative bound.

2020-12-02 22:28 UTC, jazg approved these changes

2020-12-03 09:54 UTC, loongy approved these changes

2020-12-03 09:55 UTC, merged